### ISSUE TITLE
GPL License used

### ISSUE THREAD

**Issue by felixcollins** [aster94/SensorFusion#10]
I want to make a port of your code to de-arduinofi it and use it with ESP32 IDF. Unfortunately I am doing this to use it in a commercial project. It is fine for me to fork you code, modify it and make it public but I can not release the rest of the commercial firmware. AFAICT GPL3 will require me to do this. Could you change to LGPL or MIT? That way people can include your code without having to publish their code (they still have to publish mods with LGPL). I notice that https://github.com/PaulStoffregen/MahonyAHRS has no license information at all. The MahonyAHRS.cpp file says 'From the x-io website "Open-source resources available on this website are
// provided under the GNU General Public Licence unless an alternative licence
// is provided in source."'

But the https://github.com/xioTechnologies/Fusion shows the MIT license. It is a bit of a mess. GPL is probably the wrong one to use in any case.

**Comment by aster94** [comment]
Hi @felixcollins this repo is a wrap around Paul Stoffregen's libraries. You had better to ask him about the license.
Also since I guess you are using just one between Mahony/Madgwick just put in your code the library you need and leave this library (which contains both)

**Comment by felixcollins** [comment]
I still think LGPL is more appropriate for your library.
