### ISSUE TITLE
Please make the quaternion variables accessible

### ISSUE THREAD

**Issue by SimLeek** [aster94/SensorFusion#5]
getQuat() maybe. And then a small Quaternion class to handle all four values at once.

For now I'm just going to make q0,q1,q2,q3 public for my personal stuff.

**Comment by memoore1988** [comment]
^^^

**Comment by aster94** [comment]
Feel free to make a function that returns the quaterniom

**Comment by SimLeek** [comment]
Oh hey, not dead!

I'm guessing I can make a PR then?

**Comment by aster94** [comment]
Yes sure, getQuat() seems a good name

**Comment by SimLeek** [comment]
Welp, I completely forgot about this. Gimme a second...

**Comment by SimLeek** [comment]
OK, I imagine this isn't what you want at all:

![image](https://user-images.githubusercontent.com/5911683/106097369-69e78780-60f4-11eb-8a94-d2d66b74e37c.png)

Max speed, zero variable protection so you can still write to the quats.

**Comment by SimLeek** [comment]
Sent a merge request. All the getters copy values over, so I kept that with getQuat.

**Comment by aster94** [comment]
I am closing, we can continue on the #6
