### ISSUE TITLE
getQuat isn't in the latest release

### ISSUE THREAD

**Issue by SimLeek** [aster94/SensorFusion#8]
Some people are trying to use the function, but it looks like it's not available in the latest release, so we need to do a new release: 

![image](https://user-images.githubusercontent.com/5911683/114480112-b94b3900-9bb6-11eb-9dcc-62ed0d6f4b11.png)

**Comment by aster94** [comment]
I just submitted the updated version of the library (I forgot to do this with the last PR) you should be able to download it from the IDE in a few hours (time needed by the arduino's bot to update it)

I will leave this open, if you find the new library feel free to close!

**Comment by SimLeek** [comment]
Just checked. Looks good! :+1:
